# Generated by Django 5.1.15 on 2026-08-02 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_for", models.DateTimeField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("ANSWERED", "Answered"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-scheduled_for"],
            },
        ),
        migrations.CreateModel(
            name="PingResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity", models.CharField(max_length=200)),
                ("challenge", models.PositiveSmallIntegerField()),
                ("skill", models.PositiveSmallIntegerField()),
                ("absorption", models.PositiveSmallIntegerField()),
                ("mood", models.PositiveSmallIntegerField()),
                ("wish_doing_else", models.BooleanField()),
                ("autotelic", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ping",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response",
                        to="esm.ping",
                    ),
                ),
            ],
        ),
    ]
