# Generated by Django 5.1.15 on 2026-08-02 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("goals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("DP", "Deliberate practice"),
                            ("FLOW", "Flow / performance"),
                            ("LEARN", "Learning"),
                        ],
                        max_length=5,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("duration_min", models.PositiveIntegerField()),
                ("stretch_goal", models.TextField(blank=True, default="")),
                ("feedback_received", models.TextField(blank=True, default="")),
                ("refinement", models.TextField(blank=True, default="")),
                ("discomfort", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("challenge", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("skill", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("absorption", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("enjoyment", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("had_clear_goal", models.BooleanField(blank=True, null=True)),
                ("had_immediate_feedback", models.BooleanField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="goals.goal",
                    ),
                ),
            ],
            options={"ordering": ["-started_at"],},
        ),
    ]
