# Generated by Django 5.1.15 on 2026-08-02 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("GRIT", "Grit Scale"),
                            ("MINDSET", "Mindset Assessment"),
                        ],
                        max_length=7,
                    ),
                ),
                ("taken_at", models.DateTimeField()),
                ("total_score", models.FloatField()),
                ("subscale_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-taken_at"],
            },
        ),
        migrations.CreateModel(
            name="ItemResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_number", models.PositiveSmallIntegerField()),
                ("value", models.PositiveSmallIntegerField()),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_responses",
                        to="assessments.assessment",
                    ),
                ),
            ],
            options={
                "ordering": ["item_number"],
            },
        ),
        migrations.CreateModel(
            name="ScaleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("GRIT", "Grit Scale"),
                            ("MINDSET", "Mindset Assessment"),
                        ],
                        max_length=7,
                    ),
                ),
                ("number", models.PositiveSmallIntegerField()),
                ("text", models.TextField()),
                ("reverse_scored", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["kind", "number"],
                "unique_together": {("kind", "number")},
            },
        ),
    ]
