# Generated by Django 5.1.15 on 2026-08-02 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("goals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("JOURNAL", "Journal"), ("SETBACK", "Setback")],
                        max_length=7,
                    ),
                ),
                ("body", models.TextField()),
                ("reframe", models.TextField(blank=True, default="")),
                ("fixed_score", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "growth_score",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "goal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journal_entries",
                        to="goals.goal",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "entries",
                "ordering": ["-created_at"],
            },
        ),
    ]
