# Generated by Django 5.1.15 on 2026-08-05 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeeklyReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start", models.DateField(unique=True)),
                ("what_worked", models.TextField(blank=True, default="")),
                ("what_to_change", models.TextField(blank=True, default="")),
                ("next_stretch_goal", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-week_start"],
            },
        ),
    ]
