# Generated by Django 5.1.15 on 2026-08-02 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("TOP", "Top-level"),
                            ("MID", "Mid-level"),
                            ("LOW", "Low-level"),
                        ],
                        max_length=3,
                    ),
                ),
                ("domain", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("ACHIEVED", "Achieved"),
                            ("DROPPED", "Dropped"),
                        ],
                        default="ACTIVE",
                        max_length=8,
                    ),
                ),
                ("target_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="goals.goal",
                    ),
                ),
            ],
            options={
                "ordering": ["domain", "level", "title"],
            },
        ),
    ]
