# Generated by Django 5.1.15 on 2026-08-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="is_demo",
            field=models.BooleanField(
                default=False,
                help_text="Seeded by `make seed`; removable via `make unseed`.",
            ),
        ),
    ]
